language: python
python:
- 3.7.4
dist: xenial
services:
- xvfb
install:
- pip install -r requirements.txt
script:
- python manage.py collectstatic
deploy:
  provider: heroku
  app: kranthi-rest-tutorial
  on: KN_ICTRAINING-845_Django-REST-Tutorial
  api_key:
    secure: a1vrTzooJS5qoBESO55nf2tBYOvrQWWcovzJUBuNBKZ02XujqLH+YeKWGN10lzbQlqAR9m3NRoGYMj+qpOiexEldIx/vKXT0R1jL4YsE6pPI5pdD1SWUWQDzjk/2VFTCR/EkrNTom3+Nh67oqtnD8pvXVBAN+NJpE6Mi96OhvLdb8236vWNTJnb7hyAjNilONzDvFe5OB5hGEoAk90GjI+BUI+mX5gJkGP6qrkTFuKQ3eidmkkqqXk6cX4hfdw0j4u0ip37b6AYdl4QDajcUs3DBKdCWtnCV914BylwcGO2A+1duoZeDspnKXuT5uuua1J6Mt85nhfYr0J96c4oKdXUtBtNG5jjMsWr2nL0CU5PuGKCKnB2Dtr0qa3W153H3LuG2BjoHqgkGDI8nxHqpYmCsRIMu2xF0f2XjeDSMpDkB6sFmlqw4iaacuKIUOHb3zQQili/vWRuWqus7ml9BtgnIkPex1xL7gESSCbIqgnlgmV97jE+AZinYUvDXS9XitlNpq6HcnrFYQrO+iSA+2fXbbVng8++uCj6VjELeUsNXxrsdbz0j0La813Fe8Jc2kcTDhWGZTOkZNMMiWdAxDXKOQsF4fFLJdZRgdubSqLnm4UY6Acps+73XXv1HXRF2ArUyK0zUDP47nSMs62VX3eyXWlzJz62m8Or7pzMbmOc=
